"""
AI2 Behavioral Intelligence Service — HTTP API.

This is the ONLY entry point Backend talks to. It:
  1. Receives the SessionPayload (JSON) from Backend over HTTP.
  2. Validates its shape using Pydantic (rejects malformed requests automatically).
  3. Converts it into our internal dataclasses (data_models.py).
  4. Runs it through the full pipeline (pipeline.py).
  5. Returns the structured result as JSON (matching api_contract.md).

Run locally with:
    uvicorn api:app --reload --port 8000

Interactive docs (auto-generated by FastAPI) available at:
    http://localhost:8000/docs
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from data_models import SessionPayload
from pipeline import analyze_session


# ---------------------------------------------------------------------------
# 1. Pydantic request models — define and VALIDATE the exact shape of the
#    incoming JSON. These mirror data_dictionary.md field-for-field.
# ---------------------------------------------------------------------------

class MicroChallengeIn(BaseModel):
    question_id: str
    response_time_seconds: float = Field(ge=0)
    is_correct: bool


class SectionIn(BaseModel):
    section_id: str
    concept_id: str
    section_start_time: int = 0
    section_end_time: int = 0
    time_spent_seconds: float = Field(ge=0)
    reading_speed_wpm: float = Field(ge=0)
    scroll_speed_avg_px_per_sec: float = Field(ge=0, default=0.0)
    scroll_direction_changes: int = Field(ge=0, default=0)
    content_progression_pct: float = Field(ge=0, le=100)
    section_revisit_count: int = Field(ge=0, default=0)
    interaction_count: int = Field(ge=0, default=0)
    background_count: int = Field(ge=0, default=0)
    total_background_seconds: float = Field(ge=0, default=0.0)
    micro_challenges: list[MicroChallengeIn] = []
    tab_hidden_count: int = 0


class SessionIn(BaseModel):
    user_id: str
    session_id: str
    session_start: int
    session_end: int
    sections: list[SectionIn]


# ---------------------------------------------------------------------------
# 2. The FastAPI app itself
# ---------------------------------------------------------------------------

app = FastAPI(
    title="AI2 Behavioral Intelligence Service",
    description="Analyzes learner session behavior and returns state, focus score, and recommended action per section.",
    version="0.1.0",
)


@app.get("/health")
def health_check():
    """
    Simple liveness check. Backend/infrastructure can poll this to confirm
    the service is up before sending real traffic.
    """
    return {"status": "ok"}


@app.post("/ai2/analyze-session")
def analyze_session_endpoint(payload: SessionIn):
    """
    Main endpoint. Backend calls this once, at end of session, with the
    full SessionPayload (see data_dictionary.md). Returns per-section
    results (see api_contract.md).
    """
    # payload.model_dump() converts the validated Pydantic object back into
    # a plain dict, which session_from_dict() (data_models.py) already
    # knows how to turn into our internal dataclasses.
    try:
        session = SessionPayload.from_dict(payload.model_dump())
    except (KeyError, TypeError) as exc:
        # Should be rare — Pydantic already validated the shape above —
        # but guards against any mismatch between the two layers.
        raise HTTPException(status_code=400, detail=f"Malformed payload: {exc}")

    result = analyze_session(session)
    return result